_BASE_: ../maskclippp_coco-pan_clip-convnext-base.yaml

MODEL:
  SEM_SEG_HEAD:  
    IGNORE_VALUE: 255
    NUM_CLASSES: 133
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    DEEP_SUPERVISION: True
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 200
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  MASKCLIPPP:
    VISUAL_ENCODER_F:
      NAME: "D2SwinTransformer"
      MODEL_NAME: ""  # no use
      PRETRAINED: "output/ckpts/mask2former/coco/pan/maskformer2_swin_large_IN21k_384_bs16_100ep_final_f07440.pkl"
      OUT_FEATURES: ["res2_f", "res3_f", "res4_f", "res5_f"]
      FEATURE_SUFFIX: "_f"
      FINETUNE_TYPE: "none" # no use
      PIXEL_MEAN: [123.675, 116.280, 103.530]
      PIXEL_STD: [58.395, 57.120, 57.375]
      SIZE_DIVISIBILITY: 32
      TEST_RESIZE_TYPE: "short"
      TEST_IMAGE_SIZE: 800
    SEGMENTOR:
      NAME: "Mask2FormerSegmentor"
      PRETRAINED: "output/ckpts/mask2former/coco/pan/maskformer2_swin_large_IN21k_384_bs16_100ep_final_f07440.pkl"
      IN_FEATURES: ["res2_f", "res3_f", "res4_f", "res5_f"]
      TRANSFORMER_IN_FEATURES: ["res3_f", "res4_f", "res5_f"]