train:
  batch_size_per_gpu: 2
  dataset_path: "Custom:../../ceiling_dataset_for_ViT-P" 
  OFFICIAL_EPOCH_LENGTH: 5  
  cache_dataset: false
student:
  arch: vit_large
  patch_size: 14
  num_points: 250
  num_classes: 4  
  pretrained_weights: './dinov2_vitl14_pretrain.pth'
optim:
  epochs: 30
  warmup_epochs: 0
  lr: 1e-2
crops:
  global_crops_size: [518, 518]
evaluation:
  eval_period_iterations: 500