_BASE_: ./fcclip_convnext_large_eval_ade20k.yaml

MODEL:
  MASK_ON: True
  MASK_FORMER:
    TEST:
      PANOPTIC_ON: False
      INSTANCE_ON: False

# change both the train and test dataset
DATASETS:
  TRAIN: ("ceiling_easy_train",)
  TEST: ("ceiling_easy_val",)

SOLVER:
  IMS_PER_BATCH: 2

INPUT:
  DATASET_MAPPER_NAME: "ceiling_painting" 

OUTPUT_DIR: ./train/fc-clip/pc459