_BASE_: ./ebseg_b.yaml

MODEL:
  EBSEG:
    CLIP_RESOLUTION: 0.7
    CLIP_MODEL_NAME: "ViT-L-14-336"
    FEATURE_LAST_LAYER_IDX: 18
TEST:
  EVAL_PERIOD: 100
SOLVER:
  BASE_LR: 0.00001
  IMS_PER_BATCH: 1
  MAX_ITER: 100
  CHECKPOINT_PERIOD: 100