wandb_version: 1

model:
  desc: null
  value:
    LOAD_PROPOSALS: false
    MASK_ON: true
    KEYPOINT_ON: false
    DEVICE: cuda
    META_ARCHITECTURE: OneFormer
    WEIGHTS: pretrained_weights/1280x1280_250_16_swin_l_oneformer_ade20k_160k.pth
    PIXEL_MEAN:
    - 123.675
    - 116.28
    - 103.53
    PIXEL_STD:
    - 58.395
    - 57.12
    - 57.375
    BACKBONE:
      NAME: D2SwinTransformer
      FREEZE_AT: 0
    FPN:
      IN_FEATURES: []
      OUT_CHANNELS: 256
      NORM: ''
      FUSE_TYPE: sum
    PROPOSAL_GENERATOR:
      NAME: RPN
      MIN_SIZE: 0
    ANCHOR_GENERATOR:
      NAME: DefaultAnchorGenerator
      SIZES:
      - - 32
        - 64
        - 128
        - 256
        - 512
      ASPECT_RATIOS:
      - - 0.5
        - 1.0
        - 2.0
      ANGLES:
      - - -90
        - 0
        - 90
      OFFSET: 0.0
    RPN:
      HEAD_NAME: StandardRPNHead
      IN_FEATURES:
      - res4
      BOUNDARY_THRESH: -1
      IOU_THRESHOLDS:
      - 0.3
      - 0.7
      IOU_LABELS:
      - 0
      - -1
      - 1
      BATCH_SIZE_PER_IMAGE: 256
      POSITIVE_FRACTION: 0.5
      BBOX_REG_LOSS_TYPE: smooth_l1
      BBOX_REG_LOSS_WEIGHT: 1.0
      BBOX_REG_WEIGHTS:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      SMOOTH_L1_BETA: 0.0
      LOSS_WEIGHT: 1.0
      PRE_NMS_TOPK_TRAIN: 12000
      PRE_NMS_TOPK_TEST: 6000
      POST_NMS_TOPK_TRAIN: 2000
      POST_NMS_TOPK_TEST: 1000
      NMS_THRESH: 0.7
      CONV_DIMS:
      - -1
    ROI_HEADS:
      NAME: Res5ROIHeads
      NUM_CLASSES: 80
      IN_FEATURES:
      - res4
      IOU_THRESHOLDS:
      - 0.5
      IOU_LABELS:
      - 0
      - 1
      BATCH_SIZE_PER_IMAGE: 512
      POSITIVE_FRACTION: 0.25
      SCORE_THRESH_TEST: 0.05
      NMS_THRESH_TEST: 0.5
      PROPOSAL_APPEND_GT: true
    ROI_BOX_HEAD:
      NAME: ''
      BBOX_REG_LOSS_TYPE: smooth_l1
      BBOX_REG_LOSS_WEIGHT: 1.0
      BBOX_REG_WEIGHTS:
      - 10.0
      - 10.0
      - 5.0
      - 5.0
      SMOOTH_L1_BETA: 0.0
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      POOLER_TYPE: ROIAlignV2
      NUM_FC: 0
      FC_DIM: 1024
      NUM_CONV: 0
      CONV_DIM: 256
      NORM: ''
      CLS_AGNOSTIC_BBOX_REG: false
      TRAIN_ON_PRED_BOXES: false
      USE_FED_LOSS: false
      USE_SIGMOID_CE: false
      FED_LOSS_FREQ_WEIGHT_POWER: 0.5
      FED_LOSS_NUM_CLASSES: 50
    ROI_BOX_CASCADE_HEAD:
      BBOX_REG_WEIGHTS:
      - - 10.0
        - 10.0
        - 5.0
        - 5.0
      - - 20.0
        - 20.0
        - 10.0
        - 10.0
      - - 30.0
        - 30.0
        - 15.0
        - 15.0
      IOUS:
      - 0.5
      - 0.6
      - 0.7
    ROI_MASK_HEAD:
      NAME: MaskRCNNConvUpsampleHead
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      NUM_CONV: 0
      CONV_DIM: 256
      NORM: ''
      CLS_AGNOSTIC_MASK: false
      POOLER_TYPE: ROIAlignV2
    ROI_KEYPOINT_HEAD:
      NAME: KRCNNConvDeconvUpsampleHead
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      CONV_DIMS:
      - 512
      - 512
      - 512
      - 512
      - 512
      - 512
      - 512
      - 512
      NUM_KEYPOINTS: 17
      MIN_KEYPOINTS_PER_IMAGE: 1
      NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: true
      LOSS_WEIGHT: 1.0
      POOLER_TYPE: ROIAlignV2
    SEM_SEG_HEAD:
      NAME: OneFormerHead
      IN_FEATURES:
      - res2
      - res3
      - res4
      - res5
      IGNORE_VALUE: 255
      NUM_CLASSES: 4
      CONVS_DIM: 256
      COMMON_STRIDE: 4
      NORM: GN
      LOSS_WEIGHT: 1.0
      LOSS_TYPE: hard_pixel_mining
      PROJECT_FEATURES:
      - res2
      PROJECT_CHANNELS:
      - 48
      ASPP_CHANNELS: 256
      ASPP_DILATIONS:
      - 6
      - 12
      - 18
      ASPP_DROPOUT: 0.1
      USE_DEPTHWISE_SEPARABLE_CONV: false
      MASK_DIM: 256
      TRANSFORMER_ENC_LAYERS: 6
      PIXEL_DECODER_NAME: MSDeformAttnPixelDecoder
      SEM_EMBED_DIM: 256
      INST_EMBED_DIM: 256
      DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES:
      - res3
      - res4
      - res5
      DEFORMABLE_TRANSFORMER_ENCODER_N_POINTS: 4
      DEFORMABLE_TRANSFORMER_ENCODER_N_HEADS: 8
    PANOPTIC_FPN:
      INSTANCE_LOSS_WEIGHT: 1.0
      COMBINE:
        ENABLED: true
        OVERLAP_THRESH: 0.5
        STUFF_AREA_LIMIT: 4096
        INSTANCES_CONFIDENCE_THRESH: 0.5
    RETINANET:
      NUM_CLASSES: 80
      IN_FEATURES:
      - p3
      - p4
      - p5
      - p6
      - p7
      NUM_CONVS: 4
      IOU_THRESHOLDS:
      - 0.4
      - 0.5
      IOU_LABELS:
      - 0
      - -1
      - 1
      PRIOR_PROB: 0.01
      SCORE_THRESH_TEST: 0.05
      TOPK_CANDIDATES_TEST: 1000
      NMS_THRESH_TEST: 0.5
      BBOX_REG_WEIGHTS:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      FOCAL_LOSS_GAMMA: 2.0
      FOCAL_LOSS_ALPHA: 0.25
      SMOOTH_L1_LOSS_BETA: 0.1
      BBOX_REG_LOSS_TYPE: smooth_l1
      NORM: ''
    RESNETS:
      DEPTH: 50
      OUT_FEATURES:
      - res2
      - res3
      - res4
      - res5
      NUM_GROUPS: 1
      NORM: SyncBN
      WIDTH_PER_GROUP: 64
      STRIDE_IN_1X1: false
      RES5_DILATION: 1
      RES2_OUT_CHANNELS: 256
      STEM_OUT_CHANNELS: 64
      DEFORM_ON_PER_STAGE:
      - false
      - false
      - false
      - false
      DEFORM_MODULATED: false
      DEFORM_NUM_GROUPS: 1
      RES4_DILATION: 1
      RES5_MULTI_GRID:
      - 1
      - 1
      - 1
      STEM_TYPE: basic
    IS_TRAIN: true
    IS_DEMO: false
    TEXT_ENCODER:
      WIDTH: 256
      CONTEXT_LENGTH: 77
      NUM_LAYERS: 6
      VOCAB_SIZE: 49408
      PROJ_NUM_LAYERS: 2
      N_CTX: 16
    TEST:
      SEMANTIC_ON: true
      INSTANCE_ON: false
      PANOPTIC_ON: false
      DETECTION_ON: false
      OBJECT_MASK_THRESHOLD: 0.8
      OVERLAP_THRESHOLD: 0.8
      SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: false
      TASK: semantic
    SWIN:
      PRETRAIN_IMG_SIZE: 384
      PATCH_SIZE: 4
      EMBED_DIM: 192
      DEPTHS:
      - 2
      - 2
      - 18
      - 2
      NUM_HEADS:
      - 6
      - 12
      - 24
      - 48
      WINDOW_SIZE: 12
      MLP_RATIO: 4.0
      QKV_BIAS: true
      QK_SCALE: null
      DROP_RATE: 0.0
      ATTN_DROP_RATE: 0.0
      DROP_PATH_RATE: 0.3
      APE: false
      PATCH_NORM: true
      OUT_FEATURES:
      - res2
      - res3
      - res4
      - res5
      USE_CHECKPOINT: false
    DiNAT:
      DEPTHS:
      - 3
      - 4
      - 18
      - 5
      OUT_FEATURES:
      - res2
      - res3
      - res4
      - res5
      EMBED_DIM: 64
      MLP_RATIO: 3.0
      NUM_HEADS:
      - 2
      - 4
      - 8
      - 16
      DROP_PATH_RATE: 0.2
      KERNEL_SIZE: 7
      DILATIONS:
      - - 1
        - 16
        - 1
      - - 1
        - 4
        - 1
        - 8
      - - 1
        - 2
        - 1
        - 3
        - 1
        - 4
      - - 1
        - 2
        - 1
        - 2
        - 1
      OUT_INDICES:
      - 0
      - 1
      - 2
      - 3
      QKV_BIAS: true
      QK_SCALE: null
      DROP_RATE: 0
      ATTN_DROP_RATE: 0.0
      IN_PATCH_SIZE: 4
    CONVNEXT:
      IN_CHANNELS: 3
      DEPTHS:
      - 3
      - 3
      - 27
      - 3
      DIMS:
      - 192
      - 384
      - 768
      - 1536
      DROP_PATH_RATE: 0.4
      LSIT: 1.0
      OUT_INDICES:
      - 0
      - 1
      - 2
      - 3
      OUT_FEATURES:
      - res2
      - res3
      - res4
      - res5
    ONE_FORMER:
      DEEP_SUPERVISION: true
      NO_OBJECT_WEIGHT: 0.1
      CLASS_WEIGHT: 2.0
      DICE_WEIGHT: 5.0
      MASK_WEIGHT: 5.0
      CONTRASTIVE_WEIGHT: 0.5
      CONTRASTIVE_TEMPERATURE: 0.07
      NHEADS: 8
      DROPOUT: 0.1
      DIM_FEEDFORWARD: 2048
      ENC_LAYERS: 0
      CLASS_DEC_LAYERS: 2
      DEC_LAYERS: 10
      PRE_NORM: false
      HIDDEN_DIM: 256
      NUM_OBJECT_QUERIES: 150
      NUM_OBJECT_CTX: 16
      USE_TASK_NORM: true
      TRANSFORMER_IN_FEATURE: multi_scale_pixel_decoder
      ENFORCE_INPUT_PROJ: false
      SIZE_DIVISIBILITY: 32
      TRANSFORMER_DECODER_NAME: ContrastiveMultiScaleMaskedTransformerDecoder
      TRAIN_NUM_POINTS: 12544
      OVERSAMPLE_RATIO: 3.0
      IMPORTANCE_SAMPLE_RATIO: 0.75
solver:
  desc: null
  value:
    LR_SCHEDULER_NAME: WarmupPolyLR
    MAX_ITER: 90000
    BASE_LR: 0.0001
    BASE_LR_END: 0.0
    MOMENTUM: 0.9
    NESTEROV: false
    WEIGHT_DECAY: 0.05
    WEIGHT_DECAY_NORM: 0.0
    GAMMA: 0.1
    STEPS:
    - 30000
    NUM_DECAYS: 3
    WARMUP_FACTOR: 1.0
    WARMUP_ITERS: 0
    WARMUP_METHOD: linear
    RESCALE_INTERVAL: false
    CHECKPOINT_PERIOD: 5000
    IMS_PER_BATCH: 1
    REFERENCE_WORLD_SIZE: 0
    BIAS_LR_FACTOR: 1.0
    WEIGHT_DECAY_BIAS: null
    CLIP_GRADIENTS:
      ENABLED: true
      CLIP_TYPE: full_model
      CLIP_VALUE: 0.01
      NORM_TYPE: 2.0
    AMP:
      ENABLED: true
    POLY_LR_POWER: 0.9
    POLY_LR_CONSTANT_ENDING: 0.0
    WEIGHT_DECAY_EMBED: 0.0
    OPTIMIZER: ADAMW
    BACKBONE_MULTIPLIER: 0.1
cfg_file:
  desc: null
  value: configs/ceiling_painting/swin/oneformer_swin_large_bs2_10ep.yaml
_wandb:
  desc: null
  value:
    code_path: code/train_net.py
    python_version: 3.11.0
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1749564063.0
    t:
      1:
      - 1
      - 41
      - 43
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 43
      - 49
      - 55
      - 63
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.0
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
