MODEL:
  META_ARCHITECTURE: "CATSeg"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    NAME: "CATSegHead"
    NUM_CLASSES: 4
    TRAIN_CLASS_JSON: "datasets/ceiling_painting.json" # meta data json with only class names list
    TEST_CLASS_JSON: "datasets/ceiling_painting.json" # meta data json with only class names list
    CLIP_PRETRAINED: "ViT-L/14@336px"
    PROMPT_DEPTH: 0
    PROMPT_LENGTH: 0
    TEXT_GUIDANCE_DIM: 768
    TEXT_GUIDANCE_PROJ_DIM: 128
    APPEARANCE_GUIDANCE_DIM: 768
    APPEARANCE_GUIDANCE_PROJ_DIM: 128
    DECODER_DIMS: [64, 32]
    DECODER_GUIDANCE_DIMS: [256, 128]
    DECODER_GUIDANCE_PROJ_DIMS: [32, 16]
    NUM_LAYERS: 4
    NUM_HEADS: 4
    HIDDEN_DIMS: 128
    POOLING_SIZES: [2, 2]
    FEATURE_RESOLUTION: [24, 24]
    WINDOW_SIZES: 12
    ATTENTION_TYPE: "linear"
    CLIP_FINETUNE: "attention"
  PROMPT_ENSEMBLE_TYPE: "single"
DATASETS:
  TRAIN: ("ceiling_easy_train",)
  TEST: ("ceiling_easy_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002
  MAX_ITER: 100
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BACKBONE_MULTIPLIER: 0.01
  CLIP_MULTIPLIER: 0.01
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (2560, 2560)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1280
  MAX_SIZE_TEST: 2560
  CROP:
    ENABLED: False
    TYPE: "absolute"
    SIZE: (1280, 1280)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 1280 # used in dataset mapper
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "ceiling"
TEST:
  EVAL_PERIOD: 5000
  SLIDING_WINDOW: False
  AUG:
    ENABLED: False
    MIN_SIZES: [1280, 1600, 1920, 2240, 2560]
    MAX_SIZE: 2560
    FLIP: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 16
VERSION: 2
CUDNN_BENCHMARK: True
